#!/usr/bin/with-contenv sh

find / -user 1000 -exec chown -h mysql {} \;

[ -z "${WODBY_HOME}" ] && WODBY_HOME="/srv"
[ -z "${WODBY_CONF}" ] && WODBY_CONF="${WODBY_HOME}/conf"
[ ! -d  "${WODBY_HOME}" ] && mkdir -p "${WODBY_HOME}"
[ ! -d  "${WODBY_CONF}" ] && mkdir -p "${WODBY_CONF}"
[ ! -d "${WODBY_CONF}/mysql" ] && mkdir -p "${WODBY_CONF}/mysql"

if [ ! -f "${WODBY_CONF}/mysql/my.cnf" ] && [ ! -L "/etc/mysql" ];then
        mv "/etc/mysql"/* "${WODBY_CONF}/mysql/"
        rm -rf /etc/mysql
        chown -R "${WODBY_USER}":"${WODBY_GROUP}" "${WODBY_CONF}/mysql"
        ln -nsf "${WODBY_CONF}/mysql" "/etc/mysql"
elif [ -d "${WODBY_CONF}/mysql" ] && [ ! -L "/etc/mysql" ];then
        rm -rf /etc/mysql
        ln -nsf "${WODBY_CONF}/mysql" "/etc/mysql"
fi